import React, { Component } from 'react'
import { connect } from 'react-redux'
import ReCAPTCHA from 'react-google-recaptcha'

class RecaptchaComponent extends Component {

    handleReCaptchaOnchange(value) {
        console.log("Captcha value:", value);
        console.log('..... do the business code .....')
    }

    render() {
        return (
            <div className='container'>
                <h1>ReCaptcha</h1>
                <div className='row'>
                    <div className='col-xs-12'>
                        <ReCAPTCHA
                            ref="recaptcha"
                            sitekey="<Your public site key generated by reCAPTCHA>"
                            onChange={this.handleReCaptchaOnchange.bind(this)}
                        />
                    </div>
                </div>
            </div>
        )
    }
}

function mapStateToProps(state) {
    return {}
}

export default connect(mapStateToProps, {})(RecaptchaComponent)